ci: Temporarily disable nextest-related to avoid upstream bug
```
error: failed to parse messages generated by Cargo

Caused by:
  error querying package graph

Caused by:
  unknown package ID: bin_crate 0.0.0 (path+file:///home/runner/work/cargo-llvm-cov/cargo-llvm-cov/tests/fixtures/crates/bin_crate)
error: process didn't exit successfully: `/home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/cargo nextest run --manifest-path /home/runner/work/cargo-llvm-cov/cargo-llvm-cov/tests/fixtures/crates/bin_crate/Cargo.toml --target-dir /home/runner/work/cargo-llvm-cov/cargo-llvm-cov/tests/fixtures/crates/bin_crate/target/llvm-cov-target` (exit status: 104)
```