Update ruzstd from 0.7 to 0.8
This increases MSRV since ruzstd 0.8 uses `#[expect]` attribute
stabilized in Rust 1.81 and exclusive range patterns stabilized in Rust
1.80.

```
  error[E0658]: the `#[expect]` attribute is an experimental feature
     --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ruzstd-0.8.0/src/decoding/frame.rs:116:5
      |
  116 |     #[expect(dead_code)]
      |     ^^^^^^^^^^^^^^^^^^^^
      |
      = note: see issue #54503 <https://github.com/rust-lang/rust/issues/54503> for more information

  error[E0658]: exclusive range pattern syntax is experimental
     --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ruzstd-0.8.0/src/encoding/blocks/compressed.rs:209:9
      |
  209 |         0..6 => (0b00u8, 10),
      |         ^^^^
      |
      = note: see issue #37854 <https://github.com/rust-lang/rust/issues/37854> for more information

  error[E0658]: exclusive range pattern syntax is experimental
     --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ruzstd-0.8.0/src/encoding/blocks/compressed.rs:210:9
      |
  210 |         6..1024 => (0b01, 10),
      |         ^^^^^^^
      |
      = note: see issue #37854 <https://github.com/rust-lang/rust/issues/37854> for more information

  error[E0658]: exclusive range pattern syntax is experimental
     --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ruzstd-0.8.0/src/encoding/blocks/compressed.rs:211:9
      |
  211 |         1024..16384 => (0b10, 14),
      |         ^^^^^^^^^^^
      |
      = note: see issue #37854 <https://github.com/rust-lang/rust/issues/37854> for more information

  error[E0658]: exclusive range pattern syntax is experimental
     --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ruzstd-0.8.0/src/encoding/blocks/compressed.rs:212:9
      |
  212 |         16384..262144 => (0b11, 18),
      |         ^^^^^^^^^^^^^
      |
      = note: see issue #37854 <https://github.com/rust-lang/rust/issues/37854> for more information
```