Bump MSRV to 1.87
```
error: failed to parse manifest at `/home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ruzstd-0.8.2/Cargo.toml`

Caused by:
  feature `edition2024` is required

  The package requires the Cargo feature called `edition2024`, but that feature is not stabilized in this version of Cargo (1.81.0 (2dbb1af80 2024-08-20)).
  Consider trying a newer version of Cargo (this may require the nightly release).
  See https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#edition-2024 for more information about the status of this feature.
```

```
error[E0658]: use of unstable library feature `unsigned_is_multiple_of`
  --> /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ruzstd-0.8.2/src/bit_io/bit_reader.rs:69:30
   |
69 |             assert!(self.idx.is_multiple_of(8));
   |                              ^^^^^^^^^^^^^^
   |
```

Closes #464