Bump MSRV to 1.66
toml (used by cargo-config2) requires it.

```
error: package `toml v0.7.7` cannot be built because it requires rustc 1.66.0 or newer, while the currently active rustc version is 1.65.0
```